#!/bin/sh

docker run \
    --rm \
    -i \
    -v `pwd`:`pwd` \
    -w `pwd` \
    avblink/vscode-php-wrapper \
    phpcbf --standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal "$@"

exit $?

#/root/.composer/vendor/bin/phpcbf --standard=~/.composer/vendor/drupal/coder/coder_sniffer/Drupal